### ISSUE TITLE
where is the front-end module

### ISSUE THREAD

**Issue by ashitabh** [Bluetab/td-bg#1]
where is the front-end module

**Comment by tcrossland** [comment]
There are several front-end modules in [npm](https://www.npmjs.com/search?q=%40truedat).

Feel free to contact us [here](https://www.truedat.io/contact/) if you'd like any further information about Truedat.

**Comment by ashitabh** [comment]
Hi  Tom,

Could you please point me to document which provide command to run npm front-end module for  td-bg

**Comment by ashitabh** [comment]
![image](https://user-images.githubusercontent.com/16971797/65292906-e2d8e580-db76-11e9-9396-9d8412bdaf90.png)
Where is the Web UI where you login and see all these modules
